package actions

import (
	interfaces "kiv_ups_server/game/interfaces"
	protocol "kiv_ups_server/net/tcp/protocol"
)

// ##########################################################################
// This code is generated by `go run ./generate/messages.go`. DON'T TOUCH IT!
// ##########################################################################

type AuthenticateAction struct{}

func (a AuthenticateAction) GetPlayerContexts() []interfaces.PlayerContext {
	return []interfaces.PlayerContext{DefaultContext}
}

func (a AuthenticateAction) GetMessage() protocol.Message {
	return protocol.AuthenticateMessage{}
}

func RegisterAllActions(actionDefinition *ActionDefinition) {
	actionDefinition.Register(AuthenticateAction{})
}
