################################################################################
# This code is generated by `go run ./generate/godotmessages`. DON'T TOUCH IT! #
################################################################################

extends Node

const AUTHENTICATE = 200
