##################################################################
# This code is generated by `go run ./generate`. DON'T TOUCH IT! #
##################################################################

extends Node

const KEEP_ALIVE = 100
const ACTION_ERROR = 101
const AUTHENTICATE = 200
const CREATE_LOBBY = 201
const CREATED_LOBBY_RESPONSE = 301
const DELETE_LOBBY = 202
const DELETE_LOBBY_RESPONSE = 302
const LIST_LOBBIES = 203
const LIST_LOBBIES_RESPONSE = 303
const JOIN_LOBBY = 204
const JOIN_LOBBY_RESPONSE = 304
const PLAYER_LOBBY_JOINED = 305
const LIST_LOBBY_PLAYERS = 206
const LIST_LOBBY_PLAYERS_RESPONSE = 306
const START_GAME = 207
const START_GAME_RESPONSE = 307
const PLAYER_MOVE = 400
const UPDATE_STATE = 500
