##################################################################
# This code is generated by `go run ./generate`. DON'T TOUCH IT! #
##################################################################

extends Node

const KEEP_ALIVE = 100
const ACTION_ERROR = 101
const AUTHENTICATE = 200
const CREATE_LOBBY = 201
const CREATED_LOBBY_RESPONSE = 301
const DELETE_LOBBY = 202
const DELETE_LOBBY_RESPONSE = 302
const LIST_LOBBIES = 203
const LIST_LOBBIES_RESPONSE = 303
