package actions

import (
	interfaces2 "kiv_ups_server/masterserver/interfaces"
	protocol2 "kiv_ups_server/net/tcp/protocol"
)

/*
###############################################################
# This code is generated by `go run ./scripts/generate.go`.   #
# If you want to generate the contents of this file, go to    #
# the server directory and run the command.                   #
#                                                             #
# DON'T TOUCH IT DIRECTLY! YOU WILL SUFFER!                   #
###############################################################
*/
const (
	DefaultContext      = interfaces2.PlayerContext(0)
	LobbyContext        = interfaces2.PlayerContext(1)
	InGameContext       = interfaces2.PlayerContext(2)
	LoggedInMenuContext = interfaces2.PlayerContext(3)
)

type KeepAliveAction struct{}

func (a KeepAliveAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{DefaultContext, LobbyContext, InGameContext, LoggedInMenuContext}
}

func (a KeepAliveAction) GetMessage() protocol2.Message {
	return protocol2.KeepAliveMessage{}
}

type AuthenticateAction struct{}

func (a AuthenticateAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{DefaultContext}
}

func (a AuthenticateAction) GetMessage() protocol2.Message {
	return protocol2.AuthenticateMessage{}
}

type CreateLobbyAction struct{}

func (a CreateLobbyAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LoggedInMenuContext}
}

func (a CreateLobbyAction) GetMessage() protocol2.Message {
	return protocol2.CreateLobbyMessage{}
}

type DeleteLobbyAction struct{}

func (a DeleteLobbyAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LoggedInMenuContext}
}

func (a DeleteLobbyAction) GetMessage() protocol2.Message {
	return protocol2.DeleteLobbyMessage{}
}

type ListLobbiesAction struct{}

func (a ListLobbiesAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LoggedInMenuContext}
}

func (a ListLobbiesAction) GetMessage() protocol2.Message {
	return protocol2.ListLobbiesMessage{}
}

type JoinLobbyAction struct{}

func (a JoinLobbyAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LoggedInMenuContext}
}

func (a JoinLobbyAction) GetMessage() protocol2.Message {
	return protocol2.JoinLobbyMessage{}
}

type ListLobbyPlayersAction struct{}

func (a ListLobbyPlayersAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LobbyContext}
}

func (a ListLobbyPlayersAction) GetMessage() protocol2.Message {
	return protocol2.ListLobbyPlayersMessage{}
}

type StartGameAction struct{}

func (a StartGameAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LobbyContext}
}

func (a StartGameAction) GetMessage() protocol2.Message {
	return protocol2.StartGameMessage{}
}

type GameReconnectAvailableAction struct{}

func (a GameReconnectAvailableAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LoggedInMenuContext}
}

func (a GameReconnectAvailableAction) GetMessage() protocol2.Message {
	return protocol2.GameReconnectAvailableMessage{}
}

type ReconnectAction struct{}

func (a ReconnectAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LoggedInMenuContext}
}

func (a ReconnectAction) GetMessage() protocol2.Message {
	return protocol2.ReconnectMessage{}
}

type LeaveGameAction struct{}

func (a LeaveGameAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LoggedInMenuContext, InGameContext}
}

func (a LeaveGameAction) GetMessage() protocol2.Message {
	return protocol2.LeaveGameMessage{}
}

type LeaveLobbyAction struct{}

func (a LeaveLobbyAction) GetPlayerContexts() []interfaces2.PlayerContext {
	return []interfaces2.PlayerContext{LobbyContext}
}

func (a LeaveLobbyAction) GetMessage() protocol2.Message {
	return protocol2.LeaveLobbyMessage{}
}

func RegisterAllActions(actionDefinition *ActionDefinition) {
	actionDefinition.Register(KeepAliveAction{})
	actionDefinition.Register(AuthenticateAction{})
	actionDefinition.Register(CreateLobbyAction{})
	actionDefinition.Register(DeleteLobbyAction{})
	actionDefinition.Register(ListLobbiesAction{})
	actionDefinition.Register(JoinLobbyAction{})
	actionDefinition.Register(ListLobbyPlayersAction{})
	actionDefinition.Register(StartGameAction{})
	actionDefinition.Register(GameReconnectAvailableAction{})
	actionDefinition.Register(ReconnectAction{})
	actionDefinition.Register(LeaveGameAction{})
	actionDefinition.Register(LeaveLobbyAction{})
}
