package protocol

// ##############################################################
// This code is generated by `go run ./generate`. DON'T TOUCH IT!
// ##############################################################

type KeepAliveMessage struct {
	Ping string `json:"ping"`
}

func (m KeepAliveMessage) GetTypeId() MessageType {
	return 100
}

type AuthenticateMessage struct {
	Name string `json:"name"`
}

func (m AuthenticateMessage) GetTypeId() MessageType {
	return 200
}

type CreateLobbyMessage struct {
	Name string `json:"name"`
}

func (m CreateLobbyMessage) GetTypeId() MessageType {
	return 201
}

type CreatedLobbyResponseMessage struct{}

func (m CreatedLobbyResponseMessage) GetTypeId() MessageType {
	return 301
}

func RegisterAllMessages(definition *Definition) {
	definition.Register(KeepAliveMessage{})
	definition.Register(AuthenticateMessage{})
	definition.Register(CreateLobbyMessage{})
	definition.Register(CreatedLobbyResponseMessage{})
}
